name: 企鹅读书

on:
  workflow_dispatch:
  schedule:
    - cron: '*/20 * * * *'
  repository_dispatch:
    types: reader
  # watch:
  #    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        QQREAD_BODY: ${{ secrets.QQREAD_BODY }}
        QQREAD_TIMEURL: ${{ secrets.QQREAD_TIMEURL }}
        QQREAD_TIMEHD: ${{ secrets.QQREAD_TIMEHD }}
        QQREAD_CASH: ${{ secrets.QQREAD_CASH }}
    steps:
      - name: 'checkout codes'
        run: |
          git clone https://github.com/233Bazinga/Task.git ~/Scripts
      - name: 'setup node.js'
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: 'npm install'
        if: env.QQREAD_TIMEHD
        run: |
          cd ~/Scripts
          npm install
      - name: 'run script'
        if: env.QQREAD_TIMEHD
        run: |
          cd ~/Scripts
          node reader.js
        env:          
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
