name: 微博签到

on:
  workflow_dispatch:
  schedule:
    - cron: '5 18 * * *'
  repository_dispatch:
    types: weibo
  # watch:
  #    types: started
     
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        WB_TOKEN: ${{ secrets.WB_TOKEN }}
        WB_PAY: ${{ secrets.WB_PAY }}
    steps:
      - name: 'checkout codes'
        run: |
          git clone https://github.com/Sunert/Scripts.git ~/Scripts
      - name: 'setup node.js'
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: 'npm install'
        if: env.WB_TOKEN
        run: |
          cd ~/Scripts
          npm install
      - name: 'run script'
        if: env.WB_TOKEN
        run: |
          cd ~/Scripts
          node Task/weibo.js
        env:
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
