name: 喜马拉雅

on:
    workflow_dispatch:
    schedule:
        - cron: "6,36 * * * *"
    repository_dispatch:
        types: xmly
    # watch:
    #     types: [started]

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - name: Checkout
              run: |
                git clone -b master https://github.com/sazs34/MyActions.git ~/Scripts

            - name: 'Set up Python'
              uses: actions/setup-python@v1
              with:
                  python-version: 3.7

            - name: 'Install dependencies'
              run: |
                cd ~/Scripts
                pip install -r ./requirements.txt

            - name: 'Run script'
              run: |
                cd ~/Scripts
                python3 xmly_speed.py
              env:
                  XMLY_SPEED_COOKIE: ${{ secrets.XMLY_SPEED_COOKIE || github.event.client_payload.XMLY_SPEED_COOKIE }}
                  XMLY_ACCUMULATE_TIME: ${{ secrets.XMLY_ACCUMULATE_TIME || github.event.client_payload.XMLY_ACCUMULATE_TIME }}
                  XMLY_ACCUMULATE_INDEX: ${{ secrets.XMLY_ACCUMULATE_INDEX || github.event.client_payload.XMLY_ACCUMULATE_INDEX }}
                  XMLY_ACCUMULATE_HOURS: ${{ secrets.XMLY_ACCUMULATE_HOURS || github.event.client_payload.XMLY_ACCUMULATE_HOURS }}
                  XMLY_ANDROID_AGENT: ${{ secrets.XMLY_ANDROID_AGENT || github.event.client_payload.XMLY_ANDROID_AGENT }}
                  PUSH_KEY: ${{ secrets.PUSH_KEY || github.event.client_payload.PUSH_KEY }}
                  TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN || github.event.client_payload.TG_BOT_TOKEN }}
                  TG_USER_ID: ${{ secrets.TG_USER_ID || github.event.client_payload.TG_USER_ID }}
                  SYNCURL: https://github.com/Zero-S1/xmly_speed/raw/master/xmly_speed.py
