name: 中青看点自动阅读

on:
  workflow_dispatch:
  schedule:
    - cron: '6 1-12/2 * * *'
  repository_dispatch:
    types: youthread
  # watch:
  #    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      YOUTH_READ1: ${{ secrets.YOUTH_READ1 }}
      YOUTH_READ2: ${{ secrets.YOUTH_READ2 }}
      YOUTH_READ3: ${{ secrets.YOUTH_READ3 }}
      YOUTH_READ4: ${{ secrets.YOUTH_READ4 }}
    steps:
      - name: 'checkout codes'
        run: |
          git clone https://github.com/Sunert/Scripts.git ~/Scripts
      - name: 'setup node.js'
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: 'npm install'
        run: |
          cd ~/Scripts
          npm install
      - name: 'run youth_read 1'
        if: env.YOUTH_READ1
        run: |
          cd ~/Scripts
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ1 }}

      - name: 'run youth_read 2'
        if: env.YOUTH_READ2
        run: |
          cd ~/Scripts
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ2 }}
          
      - name: 'run youth_read 3'
        if: env.YOUTH_READ3
        run: |
          cd ~/Scripts
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ3 }}
          
      - name: 'run youth_read 4'
        if: env.YOUTH_READ4
        run: |
          cd ~/Scripts
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ4 }}
