name: 中青看点

on:
  workflow_dispatch:
  schedule:
    - cron: '*/12 * * * *'
  repository_dispatch:
    types: youth
  # watch:
  #    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        YOUTH_HEADER: ${{ secrets.YOUTH_HEADER }}
        YOUTH_ARTBODY: ${{ secrets.YOUTH_ARTBODY }}
        YOUTH_REDBODY: ${{ secrets.YOUTH_REDBODY }}
        YOUTH_TIME: ${{ secrets.YOUTH_TIME }}
    steps:
      - name: 'checkout codes'
        run: |
          git clone https://github.com/Sunert/Scripts.git ~/Scripts
      - name: 'setup node.js'
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: 'npm install'
        if: env.YOUTH_HEADER
        run: |
          cd ~/Scripts
          npm install
      - name: 'run script'
        if: env.YOUTH_HEADER
        run: |
          cd ~/Scripts
          node Task/youth.js
        env:
          YOUTH_NOTIFY_CONTROL: ${{ secrets.YOUTH_NOTIFY_CONTROL }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}  
